### ISSUE TITLE
很有潜力的项目，想问下数据表格的如何绑定动态列的呢？

### ISSUE THREAD

**Issue by jveay** [MyPrintDesign/myprint#1]
感谢

**Comment by chushenshen** [comment]
<img width="1731" alt="image" src="https://github.com/user-attachments/assets/33fd85e3-af1a-4b35-8324-e001b0b86036">
<img width="1731" alt="image" src="https://github.com/user-attachments/assets/05475389-a739-48d2-9a03-6ac76b4ef360">
这里控制台有输出表格预览数据
欢迎加群讨论
![qq](https://github.com/user-attachments/assets/8bb15b5f-25a4-45cd-9cc4-f446620cc979)
